import type { CandidateTypeformSupplement } from "./types"

// Generated from the attached Typeform TSV. Rows are matched to existing mock applicants by id order.
export const candidateTypeformSupplement = [
  {
    id: "001",
    academicFile:
      "https://api.typeform.com/responses/files/d8b6e14ed9afca1385c327a1a80f2d74bdf23991bfb54bc603275ef462fbb0f3/z7628526052579_ff37ca4b9293ddf8043ac661565babc2.jpg",
    hasExperience: false,
    experienceDesc: "Tôi chưa có kinh nghiệm trong dự án game",
    portfolio: "http://113mobile.somee.com/",
    portfolioLinks: ["http://113mobile.somee.com/"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      "Xin chào quý nhà tuyển dụng em là Duy Khanh hiện là sinh viên năm cuối của Trường Cao đẳng Giao Thông Vận Tải Hồ Chí Minh. Hiện tại em vẫn đang trong quá trình học hỏi và cũng cố kiến thức cho bản thân việc tham gia thực tập tại Công ty sẽ giúp em rất nhiều trong sự nghiệp của bản thân em. Em không học trường top nhưng em tin chắc rằng khả năng của bản thân em sẽ đáp ứng được nhu cầu công việc và em vẫn sẽ phát triển thêm theo từng ngày ạ.",
    typeformSubmittedAt: "22/04/2026 8:31:53",
    typeformToken: "5i8xakjgkoge8rv39ucpqx5i8xakjg9t",
    sourceBatch: 1,
    sourcePic: "Nhiên",
    sourcePositions: "Game Design, Game UA, AI",
    screeningNote: "23/04 - 27/04: Screen hết CV đợt 1",
    note: "",
  },
  {
    id: "002",
    academicFile:
      "https://api.typeform.com/responses/files/d55b4c41d3e6682cfab98e065a4ba2da037f4ddbfc2875cf21f0ccb61883aabd/Transcript___Data_Analysis_Intern___Phạm_Ngọc_Trí.pdf",
    hasExperience: true,
    experienceDesc:
      "I have experience as a Data Analyst Intern at OFI Vietnam, where I built Power BI dashboards for QC monitoring, enabling faster issue detection and improving data consistency through automation.  In my Social Media Ads Analytics project, I built ETL pipelines and analyzed CTR/Conversion to identify optimization opportunities for campaign performance. In the Airline Loyalty Analysis project, I performed data modeling, defined KPIs, and segmented customers to improve engagement. Additionally, my thesis on Vietnamese toxic language detection involved building a 34k+ dataset and labeling pipeline, achieving high data quality and ranking #2 with a 9.5/10 score.",
    portfolio:
      "(Social Media Ads Analytics) https://github.com/triphamday/social-media-ads-datawarehouse  (Airline Loyalty Analysis) https://github.com/triphamday/airline-loyalty-analytics",
    portfolioLinks: ["https://github.com/triphamday/social-media-ads-datawarehouse", "https://github.com/triphamday/airline-loyalty-analytics"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "SUN.STUDIO LinkedIn",
    sunStudioMessage:
      "I’m genuinely excited about the opportunity to join SUN.STUDIO and contribute to data-driven product development in the game industry. I’m eager to learn, take ownership of my work, and continuously improve both my technical and product thinking skills. I would really value the chance to work in a fast-paced, collaborative environment where I can turn data into meaningful insights that enhance player experience.",
    typeformSubmittedAt: "22/04/2026 9:58:54",
    typeformToken: "q4bzy817knon6rwu7tq4bzg8wp39bqf8",
    sourceBatch: 1,
    sourcePic: "Quỳnh",
    sourcePositions: "Unity, Data",
    screeningNote: "28/04: Gửi bài test đợt 1",
    note: "",
  },
  {
    id: "003",
    academicFile:
      "https://api.typeform.com/responses/files/dd07064b4a28c99f27f523cd6e4bd40343e10d8e2a4a68ffe89b96e10ee09f98/Transcript___Unity_Developer_Intern___Nguyễn_Trọng_Nghĩa.pdf",
    hasExperience: true,
    experienceDesc:
      "Đã từng thực tập ở một công ty game, vị trí thực tập là Playable Ads Developer. Vị trí này đảm nhận công việc xây dựng và thiết kế quảng cáo mà cho người dùng tương tác. Kết quả là mình đã tạo được 2-3 quảng cáo cho công ty.  Ngoài ra còn có dự án làm game kinh dị với 3 thành viên, vị trí đảm nhiệm là thiết kế môi trường và lập trình cho hành vi và chuyển động của con ma.",
    portfolio: "https://github.com/nghiantrong/HorrorGame_Loop",
    portfolioLinks: ["https://github.com/nghiantrong/HorrorGame_Loop"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    typeformSubmittedAt: "22/04/2026 10:48:04",
    typeformToken: "cqucertyhscuypvkcquce2ag30h2hiwz",
    sourceBatch: 1,
    sourcePic: "Minh",
    sourcePositions: "QA",
    screeningNote: "04/05: Nhận lại bài test & Gửi các bên chấm bài (Đợt 1) & Gửi bài test (Đợt 2)",
    note: "",
  },
  {
    id: "004",
    academicFile:
      "https://api.typeform.com/responses/files/6f878a25a48a09d8d66d65c5bbf323c36d844c42d556da210778186126a86619/Transcript___Game_Design_Intern___Đặng_Thế_An.png",
    hasExperience: true,
    experienceDesc:
      "1.Mình có khoảng 3 năm học làm việc với Unity. ( các dự án mình đều tự làm ).Từng đi phỏng vấn và pass vòng technical ở vị trí Middle Unity Developer tại Tech Anatomy Studio.  2.Có 2 đồ án game mình làm trên trường ( đồ án cơ sở và đồ án chuyên ngành ) và đều đạt điểm 10/10.  3.Mình cũng có làm freelance và đã từng phục nhiều khách hàng với các thể loại khách nhau từ 2d - 3d và online lẫn offline. 4.Lập một kênh Youtube chia sẽ về lập trình và toán học trong lập trình game.( với hơn 30 video được chuẩn bị rất kỹ càng và chuyên nghiệp ).",
    portfolio: "Kênh Youtube : https://www.youtube.com/@HomemadeGames-v7y  Github:https://github.com/AnhAnIT/CombatFramework2D",
    portfolioLinks: ["https://www.youtube.com/@HomemadeGames-v7y", "https://github.com/AnhAnIT/CombatFramework2D"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      "Mình không chỉ muốn mang đến kinh nghiệm của một Unity Developer để giúp các dự án của SUN vận hành mượt mà, mà còn muốn cùng mọi người đi tìm lời giải cho những trải nghiệm sâu sắc và tinh tế hơn. Với mình, mỗi sản phẩm tại SUN không chỉ là một ứng dụng hay một trò chơi, mà là một tác phẩm nghệ thuật. Mình rất mong được trở thành một phần trong hành trình sáng tạo đó của các bạn!",
    typeformSubmittedAt: "22/04/2026 11:11:47",
    typeformToken: "k8h8ej4kihgxkz0k8hn6vp5bq3vrr6dn",
    sourceBatch: 1,
    screeningNote: "06-07-08/05: Ít nhất 3 buổi phỏng vấn",
    note: "",
  },
  {
    id: "005",
    academicFile:
      "https://api.typeform.com/responses/files/97994d1e71c27b89f6927f71a8c3fa5b5b17be2834b645c137c748710af45177/Transcript___Unity_Development_Intern___Nguyễn_Công_Trung.pdf",
    hasExperience: true,
    experienceDesc:
      "Lên kế hoạch phát triển dự án game cá nhân nhỏ hoặc 1 prototype về tựa game muốn làm. Sưu tầm, chỉnh sửa asset game để đưa vào unity. Tiến hành code theo kế hoạch đã đề ra từ các bước tạo object, animation từ các asset trước đó, cấu trúc folder, code và cuối cùng là build game và đưa lên web (itch.io)",
    portfolio: "https://culicoder.itch.io/shadow-dash-2d",
    portfolioLinks: ["https://culicoder.itch.io/shadow-dash-2d"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      "Em rất mong có cơ hội để làm việc tại SUN.STUDIO để được tìm hiểu và tiếp xúc với quy trình làm game thực tế mang sản phẩm đến với người chơi.",
    typeformSubmittedAt: "22/04/2026 11:34:40",
    typeformToken: "f34elene3daco7ef34elinexo3mbb44a",
    sourceBatch: 1,
    screeningNote: "14/05: Nhận bài test đợt 3 & Gửi bài test cho các bên chấm",
    note: "",
  },
  {
    id: "006",
    academicFile:
      "https://api.typeform.com/responses/files/93d0e912f21fb5f4eff357f599b83cffd626eb68d0d59edaa43030c923c03b40/Transcript_intern_TranDoHoangTan.png",
    hasExperience: true,
    experienceDesc: "Tôi code chính,design,quản lí dự án trong các Dự án 2d/3d",
    portfolio: "https://github.com/Cow040606/EcoWorld",
    portfolioLinks: ["https://github.com/Cow040606/EcoWorld"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội, TopCV",
    sunStudioMessage:
      "Tôi là sinh viên sắp ra trường mong muốn được vị trí thực tập để học hỏi cũng như tiếp thêm kiến thức chuyên nghành,cũng như muốn gắn bó lâu dài và cống hiến hết sức mình cho quý công ty ,Xin chân thành cảm ơn quý công ty đã xem",
    typeformSubmittedAt: "22/04/2026 12:07:27",
    typeformToken: "tkq524gebqz8suguori9xq0tkq5mwmop",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "007",
    academicFile:
      "https://api.typeform.com/responses/files/53679cae613e1380865f5b1c629b2b8f1558d4f3c99e17fa4fdbda1662435a60/Transcript___Game_Designer___Nguyễn_Minh_Khôi.pdf",
    hasExperience: true,
    experienceDesc:
      'Đối với dự án BarbarQ2 (Tại Gihot Studio) Vai trò: Game Design Intern. Kết quả: Nắm bắt quy trình thực tế, trực tiếp tham gia thiết kế chức năng và hoàn thiện tài liệu GDD cho các thành phần mới của game. Đối với dự án Veggie Heist (2D side-scrolling) Vai trò: Developer và Level Designer. Kết quả: Hoàn thành tài liệu GDD và phát triển thành công bản game demo chơi được. Đặc biệt, em đã thiết kế và lập trình cơ chế "Thanh Siêu Cấp" giúp thay đổi lối chơi dựa trên trạng thái cảm xúc của nhân vật.',
    portfolio: "https://surl.li/qfueni, https://surl.li/bhmajq, https://surl.li/bhmajq",
    portfolioLinks: ["https://surl.li/qfueni", "https://surl.li/bhmajq"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      "Với tư duy của một Game Designer hiểu rõ nền tảng kỹ thuật và đã có kinh nghiệm viết GDD thực tế, em rất mong muốn được trở thành một phần của SUN.STUDIO. Em đã sẵn sàng bắt tay vào việc để cùng đội ngũ tạo ra những sản phẩm chất lượng",
    typeformSubmittedAt: "22/04/2026 12:08:47",
    typeformToken: "xybrj60a3yoxudj15uxybrw5yry7volz",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "008",
    academicFile:
      "https://api.typeform.com/responses/files/72eaf3206f3e349b5ff6bbe1955faf3282b4e361c4fdd146ce90d6fd4d7ac675/Bảng_điểm__FPT_Polytechnic.pdf",
    hasExperience: true,
    experienceDesc:
      "Em đã hoàn thành tốt 3 dự án môn học , 2 dự án môn học em là nhóm trưởng và 1 dự án em là thành viên và kết quả trung bình của 3 dự án trên là 8 điểm.",
    portfolio: "https://embaotoichoi.github.io/my-profile/",
    portfolioLinks: ["https://embaotoichoi.github.io/my-profile/"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "TopCV, Mạng xã hội, SUN.STUDIO LinkedIn",
    sunStudioMessage:
      "Em rất vui và mong muốn có cơ hội được gặp gỡ, trao đổi trực tiếp với anh chị và quý công ty để được học hỏi thêm. Em hy vọng trong tương lai gần, em có thể đồng hành và phát triển cùng quý công ty trong các dự án game chất lượng cao.",
    typeformSubmittedAt: "22/04/2026 12:14:53",
    typeformToken: "6qihxwwb0ee30coxwfwgpet6qihxwwki",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "009",
    academicFile:
      "https://api.typeform.com/responses/files/b97b8597bffdb1565f56df5e19a9f4ce350f9c9cf947007ea55276e0fadaf9d5/Transcript___Game_Designer_Intern___Nguyễn_Đức_Hoàng.pdf",
    hasExperience: true,
    experienceDesc:
      "Tôi có kinh nghiệm 2-3 năm làm việc trong vị trí Developer, và đa số là dự án về puzzle và hyper, 2D, 3D. Đã từng tích hợp với SDK, ADs và IAP, có kinh nghiệm public game trên store.",
    portfolio: "https://drive.google.com/drive/folders/1yPEC87Mw-r_ciPQ2hC6jdqNbwutx3KD9?usp=sharing",
    portfolioLinks: ["https://drive.google.com/drive/folders/1yPEC87Mw-r_ciPQ2hC6jdqNbwutx3KD9?usp=sharing"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội, SUN.STUDIO LinkedIn",
    sunStudioMessage:
      "Rất mong muốn được studio để mắt tới nguyện vọng của tôi, tôi rất mong bên studio sẽ gửi mail phản hồi lại. Xin cảm ơn rất nhiều",
    typeformSubmittedAt: "22/04/2026 12:18:25",
    typeformToken: "4edddcgwdirim45ops34edddcgza6s5o",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "010",
    academicFile:
      "https://api.typeform.com/responses/files/5494a8a953acc15ac2ab77ee74255181f05412bb1fdaff82817b2eb80200d4ed/Dat_Tran_TopCV.vn_090426.223435__1___3_.pdf",
    hasExperience: true,
    experienceDesc: "Mình có kinh nghiệm thực tập tại studio nhỏ về việc Tester game viết báo cáo lỗi.và các tính năng nâng cao khác dựa theo Design",
    portfolio: "Đã tạm dừng được 2 năm.thực tập năm 3(2024)",
    portfolioLinks: ["https://m.th"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      "Tôi mong muốn được đồng hành và phát triển cùng Sun. Nếu được như thế tôi sẽ cống hiến hết mình cùng với những thành viên khác cùng theo chân mentor để cùng nhau bức phá. VẬY THÔI ! Mình Xin cảm ơn và chúc sức khỏe !",
    typeformSubmittedAt: "22/04/2026 12:23:01",
    typeformToken: "gp1r5jc2a36mbarzqhgp1rj9iw1g7d1z",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "011",
    academicFile:
      "https://api.typeform.com/responses/files/0731dc164a41b8ec3b2879feff29fef008760d47156b24640f31e0c692797a03/Transcript_Game_DesignerIntern_Trần_Quốc_An.pdf",
    hasExperience: true,
    experienceDesc:
      "Em chủ yếu phụ trách thiết kế map, UI/UX, xây dựng gameplay cơ bản cho player và lựa chọn SFX.  Dự án được đánh giá cao, và có tiềm năng phát triển đây là những lời mà giảng viên và giám khảo đánh giá dự án em tham gia ạ.",
    portfolio: "https://github.com/hotaru0906/CDOnline",
    portfolioLinks: ["https://github.com/hotaru0906/CDOnline"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      '"Em không chỉ muốn tìm một nơi để thực tập, mà mong muốn được đóng góp sức trẻ vào những dự án chất lượng của SUN.STUDIO. Em tin rằng với sự kiên trì, tư duy sáng tạo và khả năng thích nghi nhanh, em có thể là một nhân tố mới đầy tiềm năng cho team. Rất mong nhận được phản hồi từ phía Công Ty ạ"',
    typeformSubmittedAt: "22/04/2026 12:52:28",
    typeformToken: "5u8011g0yve8c56bb5u8011lelb5rnlt",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "012",
    academicFile:
      "https://api.typeform.com/responses/files/9aca8be9e7fa75bd199efca892849ef5d72dc10194bd2180dd7ace19d5c84280/Transcript___Data_Analysis_Intern___Phạm_Minh_Ngân.pdf",
    hasExperience: false,
    experienceDesc: "No",
    portfolio: "https://github.com/xxxmvppmn/FoodWaste-OLAP-Project",
    portfolioLinks: ["https://github.com/xxxmvppmn/FoodWaste-OLAP-Project"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Ybox",
    typeformSubmittedAt: "22/04/2026 12:56:43",
    typeformToken: "lpb15fhony2d9jv5ilpb15fhi12ri89e",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "013",
    academicFile:
      "https://api.typeform.com/responses/files/11c262b1979f89539b3b7dc2d373eb139a9852d1861c8d9b3cb4dcd378c73fb4/Transcript_GameDesignerIntern_VoNguyenHung.pdf",
    hasExperience: true,
    experienceDesc:
      "During my academic years, I worked as a Game Designer(main role) and Game Developer on a project that won an honorable mention at a game competition organized by FPT Polytechnic. On the professional side, I took on the same roles and successfully delivered the project on schedule as required by the client.",
    portfolio: "https://drive.google.com/drive/folders/1up0IN9ytXdY2yyhp9giNVKS7Kr7L0q_3?usp=sharing",
    portfolioLinks: ["https://drive.google.com/drive/folders/1up0IN9ytXdY2yyhp9giNVKS7Kr7L0q_3?usp=sharing"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "SUN.STUDIO LinkedIn, Mạng xã hội",
    sunStudioMessage:
      "Game design isn't just a career choice for me — it's something I committed to fully. I left my previous field to pursue this, because I realized I didn't want to spend my life doing something I wasn't passionate about. Every project I've worked on has reinforced that decision. I'm not here by accident — I'm here because this is exactly where I want to be.",
    typeformSubmittedAt: "22/04/2026 13:04:21",
    typeformToken: "adnv2lryy5n2a70izadnz2o6njgzjwy4",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "014",
    academicFile:
      "https://api.typeform.com/responses/files/c05fb2b3f238138b3fd1a4632ce82a420acb9552bceed8718df3c4bbd0e48f27/Transcript___Game_Designer_Intern___Trần_Đông_Khang.rar",
    hasExperience: true,
    experienceDesc:
      "Mình từng làm qua một số dự án cá nhân và công ty với các công việc như sau: xây dựng hệ thống Inventory, Quest System và Popup UI cho game RPG và Tower Defense. Thiết kế tài liệu GDD (Game Design Document) mô tả chi tiết gameplay loop, progression, và UI flow. Thiết kế UI tương tác trực quan thể hiện rõ tiến trình, nhiệm vụ, và phần thưởng.",
    portfolio:
      'Portfolio:" https://www.notion.so/Project-Overview-3189f5ea2d9f80d69291f9c032848b8d?source=copy_link" -- Link github: https://github.com/ShiaKhan.',
    portfolioLinks: ["https://www.notion.so/Project-Overview-3189f5ea2d9f80d69291f9c032848b8d?source=copy_link", "https://github.com/ShiaKhan"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      "Mình rất mong muốn có cơ hội được trở thành một phần của SUN.STUDIO để tham gia vào quá trình phát triển game một cách thực tế, từ việc thiết kế gameplay, playtest đến tối ưu trải nghiệm người chơi. Mình tin rằng với tinh thần học hỏi, khả năng tiếp thu feedback nhanh và sự chủ động trong công việc, mình có thể đóng góp giá trị cho team cũng như phát triển bản thân thành một Game Designer tốt hơn.",
    typeformSubmittedAt: "22/04/2026 13:25:04",
    typeformToken: "6zwvwghojnfwr6zr0ar6zwvwtt52e1ny",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "015",
    academicFile: "https://api.typeform.com/responses/files/335e05d6eda626954f9101a8aef110fcffb2885e37f918be56d762b78f2b9c51/BẢNG_ĐIỂM_HẢI_ĐĂNG.zip",
    hasExperience: true,
    experienceDesc: "những dự án indie của bản thân, và là lead của các nhóm tại trường",
    portfolio: "https://github.com/haidang0201/Shooting_Bird_2D",
    portfolioLinks: ["https://github.com/haidang0201/Shooting_Bird_2D"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội, Facebook",
    sunStudioMessage: "Mong quý công ty xem xét hồ sơ của em và cho em cơ hội, em luôn học hỏi và chủ động trong công việc",
    typeformSubmittedAt: "22/04/2026 13:26:15",
    typeformToken: "kf1cgam5qu15rkyu6kf151aisqm1sqya",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "016",
    academicFile:
      "https://api.typeform.com/responses/files/198cd9ca97b35e6dc28e70f0e3d253ddf064f8826dd590de1881e183a8f6b553/Transcript___Unity_Development_Intern___Nguyễn_Phương_Nam.pdf",
    hasExperience: false,
    experienceDesc: "Chưa có",
    portfolio: "Chưa có",
    portfolioLinks: [],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Trường đại học",
    sunStudioMessage:
      'Tôi có nền tảng tư duy logic tốt, dù là bước đầu, tôi tự tin nắm vững quy trình vận hành và cấu trúc của một trò chơi. Với sự nghiêm túc và khả năng tự học nhanh, tôi tự tin sẽ thích nghi tốt với quy trình chuyên nghiệp tại SUN.RISER."',
    typeformSubmittedAt: "22/04/2026 13:45:32",
    typeformToken: "brkljour2agfrjxflp4fkvy0brkljour",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "017",
    academicFile:
      "https://api.typeform.com/responses/files/32a39f2241d205e2501fd82b9c0e9d929733317670a5a619458cad22954c4171/Transcripts___AI_Engineering_Intern___Phan_Đình_Thái.pdf",
    hasExperience: true,
    experienceDesc: "no",
    portfolio: "https://phandinhthai012.github.io/",
    portfolioLinks: ["https://phandinhthai012.github.io/"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    typeformSubmittedAt: "22/04/2026 13:54:23",
    typeformToken: "fs66ove00aacufcbg98fs66ov9tzow17",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "018",
    academicFile:
      "https://api.typeform.com/responses/files/4539e8b37eb7173f733e1e42c7b93f135367c35feeafed0bf1a147ccd6379f95/Transcript___Game_Desiner_Intern___Ngô_Trung_Thiện.pdf",
    hasExperience: true,
    experienceDesc:
      "I developed a classic Breakout arcade game in C++ by designing a modular game engine architecture built on core OOP principles including encapsulation, inheritance, and polymorphism. Also, I implemented real-time collision detection between ball, paddle, and brick objects alongside smooth game state transitions. Lastly, I optimized memory management and object lifecycle handling to ensure stable, performant gameplay throughout the session.",
    portfolio: "https://github.com/DilysT/Break-out-game/tree/main/Breakout_game",
    portfolioLinks: ["https://github.com/DilysT/Break-out-game/tree/main/Breakout_game"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Trường đại học",
    sunStudioMessage:
      "I’m eager to learn, contribute, and grow within SUN.STUDIO while bringing a proactive and responsible mindset to the team. I hope to gain hands-on experience and deliver meaningful value to your game projects.",
    typeformSubmittedAt: "22/04/2026 13:54:42",
    typeformToken: "5s9kqictcx1gp8j5s9kqihoclafkxyo0",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "019",
    academicFile:
      "https://api.typeform.com/responses/files/53d8acbb8aa78802e0f7801cc48664ade14327d05af092b1e6c95c2043149481/bảng_điểm_Trần_Danh_Vinh.pdf",
    hasExperience: false,
    experienceDesc: "N/A",
    portfolio: "https://github.com/tdv1610",
    portfolioLinks: ["https://github.com/tdv1610"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Trường đại học",
    typeformSubmittedAt: "22/04/2026 14:06:07",
    typeformToken: "kgd0ehaqms9o8q8u0racbkgd0ehaq2at",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "020",
    academicFile:
      "https://api.typeform.com/responses/files/aec9ee77beb60ce0615124d212aa8d38203db7389e67ebca493c86f6b27aaa81/NguyenHungPhat_Academic.pdf",
    hasExperience: false,
    experienceDesc: "N/A",
    portfolio: "https://github.com/phat9824",
    portfolioLinks: ["https://github.com/phat9824"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Trường đại học",
    typeformSubmittedAt: "22/04/2026 14:16:27",
    typeformToken: "0r1wbhdoh8bhimdfuax0r1wbhs9285sf",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "021",
    academicFile:
      "https://api.typeform.com/responses/files/91e19ff99978976cf2625a4afc05055a40ef4ffd1152a89e49124b13a126ca6f/Transcript___Data_Analysis_Intern___Lê_Hữu_Tài.pdf",
    hasExperience: false,
    experienceDesc: "Không",
    portfolio: "https://github.com/huutai-le",
    portfolioLinks: ["https://github.com/huutai-le"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Trường đại học",
    typeformSubmittedAt: "22/04/2026 14:23:47",
    typeformToken: "fwrd7sfbvni0egwoigwfwrd7trg6cqku",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "022",
    academicFile: "https://api.typeform.com/responses/files/923b787408de0fc1469f099a94dece171a05d9bb13a651a811e163021e36e281/transcript.pdf",
    hasExperience: true,
    experienceDesc: "Beta game tester: testing gameplays and events before the patch is officially released",
    portfolio: "NDA",
    portfolioLinks: [],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Recommendation from friends",
    typeformSubmittedAt: "22/04/2026 14:33:04",
    typeformToken: "xr5l9z3wp0ya6uota3xr5l9bnxm2dixf",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "023",
    academicFile:
      "https://api.typeform.com/responses/files/3ae1c6dd01b726e77a59ca331c14f03236f4aa9f5498f76d7fdc55beeddcca12/Transcript___Game_Design_Intern___Tran_Phuong_Anh.pdf",
    hasExperience: true,
    experienceDesc:
      "Vai trò của em trong đồ án game là: biên kịch, 2d artist, 2d animation, UX UI. Kết quả môn đồ án game: được hội đồng đánh giá tốt và nhận được con điểm 8",
    portfolio: "https://tranphuonganhjeon.wixsite.com/tranphuonganhh",
    portfolioLinks: ["https://tranphuonganhjeon.wixsite.com/tranphuonganhh"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      "Em mong muốn được học hỏi quy trình làm việc chuẩn mực tại SUN.STUDIO và hy vọng rằng, với sự sáng tạo và năng lượng của một sinh viên năm cuối, em có thể góp phần nhỏ bé vào việc hiện thực hóa những dự án đầy tham vọng mà studio đang ấp ủ.",
    typeformSubmittedAt: "22/04/2026 14:36:00",
    typeformToken: "021uso1f71vaw542lpa9021usocr81vj",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "024",
    academicFile:
      "https://api.typeform.com/responses/files/5b8d5c4f8a8b81fc3cfe661e02895245de0c5144bc9c842e377cf580e918bfa7/Transcript___Game_Designer_Intern___Trần_Lập_Nhân.pdf",
    hasExperience: true,
    experienceDesc:
      "Em từng tham gia làm 1 tựa game kinh dị đơn giản lúc còn ở trên trường nhưng lúc đó kỹ năng còn hạn chế nên được 6.9 điểm ạ. Em có cơ hội được làm thử test Game Designer Intern bên VNG nhưng kết quả không đậu ạ.",
    portfolio: "https://www.behance.net/gallery/195606085/My-Portfolio",
    portfolioLinks: ["https://www.behance.net/gallery/195606085/My-Portfolio"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      "Dạ, em mong có thể được đậu CV để có cơ hội được học tập và thử sức làm game và có thể được đóng góp cho công ty ạ. Em cảm ơn ạ.",
    typeformSubmittedAt: "22/04/2026 14:37:21",
    typeformToken: "mlj0i0ytuapksxmmmlj0i0hrnnb2hypq",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "025",
    academicFile:
      "https://api.typeform.com/responses/files/35014d9f4fe7aad694519fb272f3f8342690521a01e44c6701d162e862e3a5c9/Transcript___Game_Designer_Intern___Dương_Thế_Khải__2_.jpg",
    hasExperience: true,
    experienceDesc:
      "Lập trình và tạo một tựa game cơ bản thể loại FPS và 2D Platforms cho các môn Software project (1,2,3) và được điểm khá cao lần lượt từng project là 8.5, 8 và 7",
    portfolio:
      "https://play.unity.com/en/games/42d2e361-a359-44e2-bea1-f47fc7822c46/adventure?zarsrc=30&utm_source=zalo&utm_medium=zalo&utm_campaign=zalo&gidzl=vewLO_t1WpJXbv1d-TcADUwPdsBlreeqfCgHPRxMWM2bp9emxDQ1DQ7DbZEvW8qqzSxBO30lU29a-yMECG",
    portfolioLinks: [
      "https://play.unity.com/en/games/42d2e361-a359-44e2-bea1-f47fc7822c46/adventure?zarsrc=30&utm_source=zalo&utm_medium=zalo&utm_campaign=zalo&gidzl=vewLO_t1WpJXbv1d-TcADUwPdsBlreeqfCgHPRxMWM2bp9emxDQ1DQ7DbZEvW8qqzSxBO30lU29a-yMECG",
    ],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage: "Rất mong được hợp tác và đồng hành cùng Sun.Studio trong thời gian tới để tạo nên những tựa game chất lượng cho Gamer",
    typeformSubmittedAt: "22/04/2026 14:43:24",
    typeformToken: "vupums02t5t89vupyifg9x0tunmeqaj1",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "026",
    academicFile:
      "https://api.typeform.com/responses/files/53ad8f672880a7ad0efc9c5717810edd9bf9e9bb9d55532b3c6a54361ab75fb9/Transcript___Unity_Development_Intern___Tạ_Ngọc_Minh.docx",
    hasExperience: false,
    experienceDesc: "Chưa từng",
    portfolio: "chưa có",
    portfolioLinks: [],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage: "Mong có thể đồng hành cùng SUN và cảm ơn SUN đã tạo cơ  hội cho mọi người.",
    typeformSubmittedAt: "22/04/2026 14:45:59",
    typeformToken: "40siskw1a0257a8kgniy40siskraegou",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "027",
    academicFile:
      "https://api.typeform.com/responses/files/09099c73385b6c3c89c638604d92734b2563b8a068b3449cfd4fdc80cc3a774e/Transcript___Data_Analysis_Intern___Đỗ_Phú_Duy.pdf",
    hasExperience: false,
    experienceDesc:
      "I don't have any personal projects related to the game industry yet, but I would be happy to learn and apply my knowledge in this field.",
    portfolio: "Linkedin: linkedin.com/in/dpduy, Github: github.com/DuyEz13",
    portfolioLinks: ["https://linkedin.com/in/dpduy", "https://github.com/DuyEz13"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Trường đại học, Mạng xã hội, SUN.STUDIO LinkedIn",
    typeformSubmittedAt: "22/04/2026 15:03:27",
    typeformToken: "jpx134j6ejstoxjpx19z2du1j4z3atka",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "028",
    academicFile:
      "https://api.typeform.com/responses/files/ba824c2d35776c0cab1213132f9388c3a26e2f462fbf85ce93cfd426426b15f8/Transcript___Data_Analysis_Intern___Lê_Hữu_Tài.pdf",
    hasExperience: false,
    experienceDesc:
      "I haven’t had the opportunity to work on related projects yet, but I’m highly interested in this field and eager to learn and gain hands-on experience.",
    portfolio: "https://github.com/huutai-le",
    portfolioLinks: ["https://github.com/huutai-le"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Trường đại học",
    typeformSubmittedAt: "22/04/2026 15:42:02",
    typeformToken: "owj5uqnw2s2ezs1yowjyty1p9ynmsrwd",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "029",
    academicFile:
      "https://api.typeform.com/responses/files/60bf3328dfba7ff81a60e6bad5534deb69e645ca825f9e7dc1069eaa805df6cb/Transcript___Data_Analysis_Intern___Nguyễn_Bình_Minh_Quân.pdf",
    hasExperience: false,
    experienceDesc: "None",
    portfolio: "https://github.com/ngoncovenduoq",
    portfolioLinks: ["https://github.com/ngoncovenduoq"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Nhân viên công ty giới thiệu",
    internalReferrer: "Trương Anh Khoa",
    sunStudioMessage:
      "Thank you for considering my application. I’m excited about the opportunity to learn and contribute at SUN.STUDIO, and I’m happy to provide any additional information if needed.",
    typeformSubmittedAt: "22/04/2026 15:57:05",
    typeformToken: "drigco307hwvpsodrigcyyb4u1ra9b8n",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "030",
    academicFile:
      "https://api.typeform.com/responses/files/6be9ec4d71904347ff7f5f8e5faab8d1dbb6e7d05e2054f9b7dac2e952d52196/Transcript___AI_Engineer_Intern___Nguyễn_Đình_Quân.pdf",
    hasExperience: false,
    experienceDesc:
      "I do not have direct game-related experience yet. However, I have worked on AI projects such as computer vision and recommendation systems, where I built models and worked with real-world data, and I am eager to learn and apply my skills in the game industry.",
    portfolio: "https://www.linkedin.com/in/quannguyendinh/",
    portfolioLinks: ["https://www.linkedin.com/in/quannguyendinh/"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Trường đại học",
    sunStudioMessage:
      "I am very interested in the opportunity to learn and contribute at SUN.STUDIO. I would also like to learn more about how AI is applied in real game development workflows.",
    typeformSubmittedAt: "22/04/2026 16:07:00",
    typeformToken: "hc4e195cf52bhkshc4e19iewmxqhmwq6",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "031",
    academicFile:
      "https://api.typeform.com/responses/files/7d5e3c597cb8e8623d929aa60f9a6c8b3456bf567dbe0f3767767997bc3f584f/Transcript___Game_Design_Intern___Nguyễn_Trương_Trọng_Hiếu.pdf",
    hasExperience: true,
    experienceDesc:
      "Dự án gần đây nhất của em là capstone project để tốt nghiệp. Em làm nhóm 2 người. Ngoài phụ trách phân công, lên kế hoạch, em phối hợp lên ý tưởng gameplay, thiết kế feedback UI, cut scene trong game. Ngoài ra, em cũng xây dựng 1 vài hệ thống quản lý game, 1 phần gameplay.",
    portfolio: "https://drive.google.com/file/d/1HxEtcMO8zWRfg5BxIBgA3idMNYzM_4GA/view?usp=sharing",
    portfolioLinks: ["https://drive.google.com/file/d/1HxEtcMO8zWRfg5BxIBgA3idMNYzM_4GA/view?usp=sharing"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    typeformSubmittedAt: "22/04/2026 16:46:23",
    typeformToken: "k0jjonlmxrlb7pbk0jjcrli7vbss0zsk",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "032",
    academicFile:
      "https://api.typeform.com/responses/files/a09f4b7079ae962825f80e6fd51a202be38f1853e4f8ed8f0472c78f081cf6cc/BangDiem2_GameDesigner_Intern_NguyenKhacKy.jpg",
    hasExperience: true,
    experienceDesc:
      "Tôi đã thực tập tại Gihot, nơi tôi được học kiến thức nền tảng về Game Design, quy trình làm việc và các chỉ số vận hành game. Tôi cũng đã viết Game Design Document về chế độ chơi mới của game BBQ2.",
    portfolio:
      "https://docs.google.com/spreadsheets/d/1Z2sy0iIVYIgvID-2GslEQJGdTSdNt5hj/edit?usp=drive_link&ouid=113921569029709747633&rtpof=true&sd=true",
    portfolioLinks: [
      "https://docs.google.com/spreadsheets/d/1Z2sy0iIVYIgvID-2GslEQJGdTSdNt5hj/edit?usp=drive_link&ouid=113921569029709747633&rtpof=true&sd=true",
    ],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      "Tôi rất mong muốn có cơ hội được trở thành thực tập sinh tại Sun Studio. Tôi sẵn sàng học hỏi, cải thiện kỹ năng Game Design và tích lũy kinh nghiệm trong môi trường chuyên nghiệp. Đồng thời, tôi cũng hy vọng có thể đóng góp những ý tưởng và giá trị của mình cho đội ngũ trong quá trình làm việc.",
    typeformSubmittedAt: "22/04/2026 17:27:32",
    typeformToken: "dt21ozjilbrq77dt21kv4hnrta8xg7c8",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "033",
    academicFile:
      "https://api.typeform.com/responses/files/b8b1562d43425dba367af235ec6038d28ddb7a26e29081acc6c76e4ec9ea0154/CV___Unity_Developer_Intern__Phạm_Thanh_Phong.JPG",
    hasExperience: false,
    experienceDesc:
      "I have practical experience with C# through a university project where I developed a Hotel Management System using Winforms. I was responsible for implementing the business logic and managing the database. This project helped me master OOP principles and UI handling in C#, which are essential skills that I can immediately apply to learning and developing in Unity.",
    portfolio: "https://github.com/ZiKPham/HotelManagementApplication",
    portfolioLinks: ["https://github.com/ZiKPham/HotelManagementApplication"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Ybox",
    sunStudioMessage:
      "As a recent Software Engineering graduate, I am highly motivated to pursue a career in the gaming industry. I bring a strong foundation in programming logic and a proactive learning mindset. I am eager to join Sun Studio's professional environment to contribute my technical skills toward creating successful products while continuously developing myself to grow alongside the company.",
    typeformSubmittedAt: "22/04/2026 18:03:31",
    typeformToken: "zhd1hfp21yakf7754zhdo5299ggd3iyt",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "034",
    academicFile:
      "https://api.typeform.com/responses/files/a6e0d3abf8eb69cad3e142b58af381177c5b4266e7fe4957923348bf4aac3051/Bảng_điểm__FPT_Polytechnic.pdf",
    hasExperience: true,
    experienceDesc:
      'Tham gia dự án game nhóm "Xoul\'s Era" với vai trò Game Designer & Unity Developer: chịu trách nhiệm thiết kế cốt truyện, xây dựng hệ thống gameplay (chỉ số nhân vật, item), đồng thời phát triển và triển khai UI/UX trong Unity. Dự án giúp tôi tích lũy kinh nghiệm thực tế về thiết kế và phát triển game và sever của game.  https://vnexpress.net/cong-nghe/vgv-2025/du-an/xoul-s-era-239',
    portfolio: "https://drive.google.com/drive/folders/17Qhha8fPtMw5hK34qnOXQhIsu8JOmnhy",
    portfolioLinks: ["https://drive.google.com/drive/folders/17Qhha8fPtMw5hK34qnOXQhIsu8JOmnhy"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      "Tôi rất mong có cơ hội được học hỏi và phát triển tại SUN.STUDIO, đồng thời đóng góp vào việc xây dựng những sản phẩm game chất lượng. Tôi luôn chủ động cải thiện kỹ năng và sẵn sàng thích nghi để mang lại giá trị tốt nhất cho công ty.",
    typeformSubmittedAt: "22/04/2026 18:30:56",
    typeformToken: "e20ajqy7g1z2ypean3e20ajqyfc9kk6n",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "035",
    academicFile:
      "https://api.typeform.com/responses/files/8e6c5ea4417ac3f6a729c61e81f8c6700aa35d3cc1c9af0bad0d83516199b8c2/Transcript___Game_Design_Intern___Vũ_Trường_Hùng.pdf",
    hasExperience: true,
    experienceDesc:
      "Twin Blades (Multiplayer): Tìm hiểu và triển khai cơ chế đồng bộ hóa nhân vật, AI và hệ thống vật phẩm thông qua Mirror Networking. Void Seeker (Top-down Shooter): Tự xây dựng logic di chuyển, chiến đấu và hệ thống chỉ số nhân vật (RPG stat system).",
    portfolio: "https://hungvu.itch.io/void-seaker",
    portfolioLinks: ["https://hungvu.itch.io/void-seaker"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "bạn bè giới thiệu",
    sunStudioMessage:
      "Em mong muốn được học hỏi tư duy thiết kế hệ thống và cách cân bằng gameplay thực tế tại studio. Với nền tảng kỹ thuật sẵn có, em hy vọng sẽ hiểu sâu hơn về cách kết nối giữa ý tưởng thiết kế và triển khai kỹ thuật để tạo ra những trải nghiệm game cuốn hút",
    typeformSubmittedAt: "22/04/2026 19:36:16",
    typeformToken: "zjhpnbdes9q1tzjhpnmrexazti1r9khk",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "036",
    academicFile:
      "https://api.typeform.com/responses/files/4f7acd8cd9f1fb6e6d09aea2d7944957c9b3da0c0a79b61b74c8dda816ecdbe5/Transcript____Unity_Developer_Intern___Lê_Đình_Thiện.jpg",
    hasExperience: true,
    experienceDesc:
      "Dạ em trước đây em có thực hiện một số dự án game mobile, nhưng tiêu biểu là 2 dự án outsource do em phụ trách toàn bộ phần gameplay, UI và xử lý logic theo yêu cầu của khách hàng, phối hợp với team design để hoàn thiện game, kết quả là 2 game đã hoàn thiện và bàn giao toàn bộ cho khách ạ. Ngoài ra gần đây em có đang tham gia phát triển một dự án game PC cùng một thành viên khác, em phụ trách UI, gameplay và một số cơ chế màn chơi, thành viên còn lại phụ trách animation và phần còn lại",
    portfolio: "https://drive.google.com/drive/folders/1_NjdY_zSRoZhGjL-7oPmn3UvNe1fl-lr",
    portfolioLinks: ["https://drive.google.com/drive/folders/1_NjdY_zSRoZhGjL-7oPmn3UvNe1fl-lr"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Mạng xã hội",
    sunStudioMessage:
      "Dạ em định hướng theo game developer lâu dài và mong muốn được làm việc trong môi trường chuyên nghiệp để nâng cao năng lực và hiểu rõ hơn về quy trình phát triển game thực tế. Em sẵn sàng bắt đầu từ vị trí intern để học hỏi và phát triển bản thân.",
    typeformSubmittedAt: "22/04/2026 19:59:05",
    typeformToken: "ad7het09e02y0t7dd3o9ad7hetz1zqb6",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "037",
    academicFile: "https://api.typeform.com/responses/files/62eb95305329d9838576d4744feb39ab794350739e79024a34d0da728b02647e/IMG_1720.jpeg",
    hasExperience: true,
    experienceDesc: "Tham gia các cuộc thi vẽ do VNG - Play Together tổ chức",
    portfolio: "https://drive.google.com/file/d/1hyPJPqg3cZ8XCWQd3b_Foc-AoJwjKiQ1/view?usp=drivesdk",
    portfolioLinks: ["https://drive.google.com/file/d/1hyPJPqg3cZ8XCWQd3b_Foc-AoJwjKiQ1/view?usp=drivesdk"],
    internshipCommitment:
      "Em cam kết làm việc được tối thiểu 3,5 ngày/ tuần, nhưng em xin phép quý công ty đóng dấu mộc khi đến hạn nộp Thực tập cho trường, và sau đó em xin cam kết làm đủ 3 tháng như thoả thuận.",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Ybox",
    sunStudioMessage:
      "Em mong sẽ được đồng hành cùng với SUN.STUDIO, được góp phần và học hỏi môi trường mới những kinh nghiệm mới để đem lại những giá trị cho quý công ty.",
    typeformSubmittedAt: "22/04/2026 21:21:40",
    typeformToken: "hf5whe8u0k1c7zx7ihf5whfnfx7enij1",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "038",
    academicFile:
      "https://api.typeform.com/responses/files/50511fecc58f8658467cbe03ad28330c1c26e5238b0fafbee680021fd2887584/Transcript___Unity_Development_Intern___Nguyễn_Anh_Tường.png",
    hasExperience: true,
    experienceDesc:
      'Dự án thực tập tại trường tôi đã tự thực hiện đề tài "xây dựng AI trong lập trình game". Ở dự án này tôi đã xây dựng một game nhỏ áp dụng Behavior tree, A* cho pathfinding, KD-tree để phân hoạch không gian, AABB để phát hiện va chạm,... trên framework MonoGame. Kết quả nhận được đánh giá cao của hội đồng và được 8.00 cuối môn.',
    portfolio: "https://anhtuong6904.itch.io/demotribe",
    portfolioLinks: ["https://anhtuong6904.itch.io/demotribe"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "SUN.STUDIO LinkedIn, Mạng xã hội",
    sunStudioMessage: "Tôi mong được đồng hành với SUN.STUDIO trong chặng đường sắp tới để được học hỏi và cống hiến sức trẻ của mình.",
    typeformSubmittedAt: "22/04/2026 23:49:52",
    typeformToken: "o980wdf96nn6occ0nuk3eqz7ibnk1cc0",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "039",
    academicFile:
      "https://api.typeform.com/responses/files/dd6850e19856682ebf44057545d6322d95f861ef2526e22a64bae0e19d093ff2/Transcript___Data_Analysis_Intern___Võ_Ngọc_Duy.pdf",
    hasExperience: false,
    experienceDesc: "Chưa có",
    portfolio: "vnd.id.vn",
    portfolioLinks: ["https://vnd.id.vn"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "SUN.STUDIO LinkedIn",
    sunStudioMessage: "Không",
    typeformSubmittedAt: "23/04/2026 1:21:44",
    typeformToken: "l2vv3q5foeqdainbd81by5ql2vvdzf2e",
    sourceBatch: 1,
    note: "",
  },
  {
    id: "040",
    academicFile:
      "https://api.typeform.com/responses/files/fece274dc73e25ad7a4def9371339d35e70a4e18ed7fe7148d03b46c0860de84/Transcript___Game_Design_Intern___Đinh_Thanh_Tùng.pdf",
    hasExperience: true,
    experienceDesc:
      "mình đã từng tham gia thiết kế một tựa game Metroidvaina trong một môn học. Trong đó, mình đảm nhận vai trò thiết kế màn chơi, luật chơi, cốt truyện và hệ thống combat. Kết quả là nhóm mình đã được 9.5/10 cho môn học đó và được nhận giải thưởng nhóm xuất sắc nhất do hội đồng bình chọn.",
    portfolio: "https://drive.google.com/file/d/1pYfORHL0BnjjR8Jp1-8pQlmgXOouYi1I/view?usp=drive_link",
    portfolioLinks: ["https://drive.google.com/file/d/1pYfORHL0BnjjR8Jp1-8pQlmgXOouYi1I/view?usp=drive_link"],
    internshipCommitment: "Yes / Có",
    postInternshipFullTime: "Yes / Có",
    discoveryChannel: "Trường đại học",
    sunStudioMessage: "Nếu được mình rất mong có thể trở thành một thành viên và có thể gắn bó lâu dài với studio",
    typeformSubmittedAt: "23/04/2026 1:57:19",
    typeformToken: "esvwo8wgnuvy76j0ila1gesvwo8wcci9",
    sourceBatch: 1,
    note: "",
  },
] satisfies CandidateTypeformSupplement[]
