import { Applicant, DashboardStats } from './types'

export const mockApplicants: Applicant[] = [
  {
    id: '001',
    name: 'Nguyễn Minh Khoa',
    dob: '2003-04-12',
    email: 'minhkhoa.nguyen@gmail.com',
    phone: '0901234567',
    position1: 'AI Engineering Intern',
    position2: 'Data Analysis Intern',
    university: 'UIT',
    yearOfStudy: 'Năm 3',
    major: 'Khoa học máy tính',
    gpa: 8.9,
    hasExperience: true,
    experienceDesc: 'Đã tham gia dự án AI chatbot tại công ty startup 6 tháng',
    portfolio: 'https://github.com/minhkhoa',
    fullTime: true,
    discoveryChannel: 'Facebook',
    submittedAt: '2026-04-23T09:15:00Z',
    batch: 1,
    pic: 'Quỳnh',
    round1Result: 'Passed',
    round1Notes: 'Strong Python skills, good ML background',
    round2Result: 'Passed',
  },
  {
    id: '002',
    name: 'Trần Thị Hương Lan',
    dob: '2002-09-25',
    email: 'huonglan.tran@yahoo.com',
    phone: '0912345678',
    position1: 'Game Design Intern',
    university: 'HCMUT',
    yearOfStudy: 'Năm 4',
    major: 'Thiết kế đồ họa',
    gpa: 8.2,
    hasExperience: true,
    experienceDesc: 'Freelance game designer, đã thiết kế 3 mobile game indie',
    portfolio: 'https://behance.net/huonglan',
    fullTime: false,
    discoveryChannel: 'LinkedIn',
    submittedAt: '2026-04-23T10:30:00Z',
    batch: 1,
    pic: 'Nhiên',
    round1Result: 'Passed',
    round1Notes: 'Excellent portfolio, creative designs',
  },
  {
    id: '003',
    name: 'Lê Văn Đức',
    dob: '2004-01-08',
    email: 'vanduc.le@student.hcmut.edu.vn',
    phone: '0923456789',
    position1: 'Unity Development Intern',
    position2: 'Game Quality Assurance Intern',
    university: 'HCMUT',
    yearOfStudy: 'Năm 2',
    major: 'Kỹ thuật phần mềm',
    gpa: 7.8,
    hasExperience: false,
    fullTime: true,
    discoveryChannel: 'Bạn bè giới thiệu',
    submittedAt: '2026-04-23T14:22:00Z',
    batch: 1,
    pic: 'Yến',
    round1Result: 'Failed',
    round1Notes: 'Lack of practical experience',
  },
  {
    id: '004',
    name: 'Phạm Thị Ngọc Anh',
    dob: '2003-06-17',
    email: 'ngocanh.pham@fpt.edu.vn',
    phone: '0934567890',
    position1: 'Human Resources Intern',
    university: 'FPT University',
    yearOfStudy: 'Năm 3',
    major: 'Quản trị nhân lực',
    gpa: 9.1,
    hasExperience: true,
    experienceDesc: 'Thực tập tại HR department của tập đoàn lớn 3 tháng',
    fullTime: true,
    discoveryChannel: 'Website công ty',
    submittedAt: '2026-04-23T11:05:00Z',
    batch: 1,
    pic: 'Minh',
    round1Result: 'Passed',
    round1Notes: 'Strong HR background, excellent communication',
    round2Result: 'Passed',
  },
  {
    id: '005',
    name: 'Võ Hoàng Nam',
    dob: '2002-11-30',
    email: 'hoangnam.vo@gmail.com',
    phone: '0945678901',
    position1: 'Data Analysis Intern',
    position2: 'AI Engineering Intern',
    university: 'UEH',
    yearOfStudy: 'Năm 4',
    major: 'Kinh tế số',
    gpa: 8.6,
    hasExperience: true,
    experienceDesc: 'Power BI và SQL, đã làm analytics cho dự án e-commerce',
    portfolio: 'https://github.com/hoangnam-vo',
    fullTime: true,
    discoveryChannel: 'Facebook',
    submittedAt: '2026-04-24T08:45:00Z',
    batch: 1,
    pic: 'Quỳnh',
    round1Result: 'Passed',
    round1Notes: 'Good analytical skills',
  },
  {
    id: '006',
    name: 'Đặng Thị Thu Hà',
    dob: '2003-03-20',
    email: 'thuha.dang@huflit.edu.vn',
    phone: '0956789012',
    position1: 'Game User Acquisition Intern',
    university: 'HUFLIT',
    yearOfStudy: 'Năm 3',
    major: 'Marketing số',
    gpa: 7.5,
    hasExperience: false,
    fullTime: false,
    discoveryChannel: 'Instagram',
    submittedAt: '2026-04-24T13:10:00Z',
    batch: 1,
    pic: 'Nhiên',
    round1Result: 'Failed',
    round1Notes: 'Insufficient marketing experience',
  },
  {
    id: '007',
    name: 'Bùi Quốc Huy',
    dob: '2001-07-14',
    email: 'quochuy.bui@uit.edu.vn',
    phone: '0967890123',
    position1: 'AI Engineering Intern',
    university: 'UIT',
    yearOfStudy: 'Năm 4',
    major: 'Trí tuệ nhân tạo',
    gpa: 9.3,
    hasExperience: true,
    experienceDesc: 'Research assistant tại AI Lab, có 2 bài báo khoa học',
    portfolio: 'https://github.com/quochuy-bui',
    fullTime: true,
    discoveryChannel: 'LinkedIn',
    submittedAt: '2026-04-25T07:30:00Z',
    batch: 1,
    pic: 'Yến',
    round1Result: 'Passed',
    round1Notes: 'Outstanding AI research background',
    round2Result: 'Passed',
  },
  {
    id: '008',
    name: 'Nguyễn Thị Khánh Vy',
    dob: '2004-02-28',
    email: 'khanhvy.nguyen@gmail.com',
    phone: '0978901234',
    position1: 'Game Quality Assurance Intern',
    position2: 'Unity Development Intern',
    university: 'HUTECH',
    yearOfStudy: 'Năm 2',
    major: 'Công nghệ thông tin',
    gpa: 7.2,
    hasExperience: false,
    fullTime: true,
    discoveryChannel: 'TikTok',
    submittedAt: '2026-05-01T09:00:00Z',
    batch: 2,
    pic: 'Minh',
    round1Result: 'Waiting list',
    round1Notes: 'Potential but needs more experience',
  },
  {
    id: '009',
    name: 'Trịnh Minh Tú',
    dob: '2003-10-05',
    email: 'minhtu.trinh@fpt.edu.vn',
    phone: '0989012345',
    position1: 'Unity Development Intern',
    university: 'FPT University',
    yearOfStudy: 'Năm 3',
    major: 'Lập trình game',
    gpa: 8.8,
    hasExperience: true,
    experienceDesc: 'Đã phát triển 5 game Unity, 2 game đã publish trên app store',
    portfolio: 'https://github.com/minhtu-trinh',
    fullTime: true,
    discoveryChannel: 'Discord community',
    submittedAt: '2026-05-01T10:15:00Z',
    batch: 2,
    pic: 'Quỳnh',
    round1Result: 'Passed',
    round1Notes: 'Strong Unity portfolio',
    round2Result: 'Passed',
  },
  {
    id: '010',
    name: 'Lý Thị Bảo Châu',
    dob: '2002-12-15',
    email: 'baochau.ly@ueh.edu.vn',
    phone: '0990123456',
    position1: 'Data Analysis Intern',
    university: 'UEH',
    yearOfStudy: 'Năm 4',
    major: 'Thống kê kinh tế',
    gpa: 8.4,
    hasExperience: true,
    experienceDesc: 'Internship tại Deloitte 6 tháng, chuyên data visualization',
    portfolio: 'https://public.tableau.com/baochau',
    fullTime: false,
    discoveryChannel: 'Email newsletter',
    submittedAt: '2026-05-01T14:30:00Z',
    batch: 2,
    pic: 'Nhiên',
    round1Result: 'Passed',
    round1Notes: 'Good data skills, Deloitte experience impressive',
  },
  {
    id: '011',
    name: 'Phan Văn Khải',
    dob: '2003-05-22',
    email: 'vankhai.phan@gmail.com',
    phone: '0901234568',
    position1: 'Game User Acquisition Intern',
    university: 'RMIT Vietnam',
    yearOfStudy: 'Năm 3',
    major: 'Digital Marketing',
    gpa: 6.8,
    hasExperience: true,
    experienceDesc: 'Đã chạy campaign Facebook Ads, Google Ads cho 2 mobile games',
    fullTime: true,
    discoveryChannel: 'Facebook',
    submittedAt: '2026-05-02T08:00:00Z',
    batch: 2,
    pic: 'Yến',
    round1Result: 'Failed',
    round1Notes: 'GPA below threshold',
  },
  {
    id: '012',
    name: 'Hoàng Thị Mỹ Duyên',
    dob: '2004-08-09',
    email: 'myduyen.hoang@gmail.com',
    phone: '0912345679',
    position1: 'Human Resources Intern',
    university: 'NEU',
    yearOfStudy: 'Năm 2',
    major: 'Quản trị kinh doanh',
    gpa: 8.0,
    hasExperience: false,
    fullTime: true,
    discoveryChannel: 'Zalo',
    submittedAt: '2026-05-02T09:20:00Z',
    batch: 2,
    pic: 'Minh',
    round1Result: 'Passed',
    round1Notes: 'Good academic record, motivated candidate',
  },
  {
    id: '013',
    name: 'Đỗ Thanh Tùng',
    dob: '2001-03-11',
    email: 'thanhtung.do@uit.edu.vn',
    phone: '0923456790',
    position1: 'AI Engineering Intern',
    position2: 'Unity Development Intern',
    university: 'UIT',
    yearOfStudy: 'Năm 4',
    major: 'Khoa học máy tính',
    gpa: 9.0,
    hasExperience: true,
    experienceDesc: 'Machine learning engineer tại startup fintech 8 tháng',
    portfolio: 'https://github.com/thanhtung-do',
    fullTime: true,
    discoveryChannel: 'LinkedIn',
    submittedAt: '2026-05-03T11:45:00Z',
    batch: 2,
    pic: 'Quỳnh',
    round1Result: 'Passed',
    round1Notes: 'Top candidate, excellent ML skills',
    round2Result: 'Passed',
  },
  {
    id: '014',
    name: 'Vũ Thị Lan Anh',
    dob: '2003-07-30',
    email: 'lananh.vu@hcmut.edu.vn',
    phone: '0934567891',
    position1: 'Game Design Intern',
    university: 'HCMUT',
    yearOfStudy: 'Năm 3',
    major: 'Công nghệ thông tin',
    gpa: 7.6,
    hasExperience: false,
    fullTime: false,
    discoveryChannel: 'Bạn bè giới thiệu',
    submittedAt: '2026-05-03T15:00:00Z',
    batch: 2,
    pic: 'Nhiên',
    round1Result: 'Failed',
    round1Notes: 'No design portfolio',
  },
  {
    id: '015',
    name: 'Cao Thành Đạt',
    dob: '2002-01-25',
    email: 'thanhdat.cao@gmail.com',
    phone: '0945678902',
    position1: 'Game Quality Assurance Intern',
    university: 'HUFLIT',
    yearOfStudy: 'Năm 4',
    major: 'Kỹ thuật phần mềm',
    gpa: 7.9,
    hasExperience: true,
    experienceDesc: 'QA tester tại công ty game mobile 4 tháng',
    fullTime: true,
    discoveryChannel: 'Facebook',
    submittedAt: '2026-05-04T08:30:00Z',
    batch: 2,
    pic: 'Yến',
    round1Result: 'Passed',
    round1Notes: 'Relevant QA experience',
  },
  {
    id: '016',
    name: 'Ngô Quỳnh Như',
    dob: '2004-04-18',
    email: 'quynhnhu.ngo@gmail.com',
    phone: '0956789013',
    position1: 'Data Analysis Intern',
    university: 'UIT',
    yearOfStudy: 'Năm 2',
    major: 'Hệ thống thông tin',
    gpa: 8.7,
    hasExperience: false,
    portfolio: 'https://github.com/quynhnhu-ngo',
    fullTime: true,
    discoveryChannel: 'TikTok',
    submittedAt: '2026-05-05T10:00:00Z',
    batch: 2,
    pic: 'Minh',
    round1Result: 'Waiting list',
    round1Notes: 'Good GPA, limited practical experience',
  },
  {
    id: '017',
    name: 'Lâm Tuấn Kiệt',
    dob: '2003-09-07',
    email: 'tuankiet.lam@fpt.edu.vn',
    phone: '0967890124',
    position1: 'Unity Development Intern',
    university: 'FPT University',
    yearOfStudy: 'Năm 3',
    major: 'Game Development',
    gpa: 8.3,
    hasExperience: true,
    experienceDesc: 'Đã tham gia game jam, xếp hạng top 10 toàn quốc',
    portfolio: 'https://itch.io/tuankiet',
    fullTime: true,
    discoveryChannel: 'Discord community',
    submittedAt: '2026-05-06T09:15:00Z',
    batch: 2,
    pic: 'Quỳnh',
    round1Result: 'Passed',
    round1Notes: 'Game jam achievement very impressive',
    round2Result: 'Waiting list',
  },
  {
    id: '018',
    name: 'Trần Bảo Ngọc',
    dob: '2002-06-03',
    email: 'baongoc.tran@nefu.edu.vn',
    phone: '0978901235',
    position1: 'Human Resources Intern',
    position2: 'Game User Acquisition Intern',
    university: 'NEU',
    yearOfStudy: 'Năm 4',
    major: 'Tâm lý học tổ chức',
    gpa: 8.5,
    hasExperience: true,
    experienceDesc: 'HR intern tại Vingroup 3 tháng, phụ trách onboarding',
    fullTime: false,
    discoveryChannel: 'LinkedIn',
    submittedAt: '2026-05-07T13:00:00Z',
    batch: 2,
    pic: 'Nhiên',
    round1Result: 'Passed',
    round1Notes: 'Strong HR foundation',
  },
  {
    id: '019',
    name: 'Huỳnh Gia Phát',
    dob: '2003-12-01',
    email: 'giaphat.huynh@gmail.com',
    phone: '0989012346',
    position1: 'AI Engineering Intern',
    university: 'HCMUT',
    yearOfStudy: 'Năm 3',
    major: 'Điện tử viễn thông',
    gpa: 7.4,
    hasExperience: false,
    fullTime: true,
    discoveryChannel: 'Website công ty',
    submittedAt: '2026-05-08T08:45:00Z',
    batch: 2,
    pic: 'Yến',
    round1Result: 'Failed',
    round1Notes: 'Misaligned major, needs CS fundamentals',
  },
  {
    id: '020',
    name: 'Đinh Thị Hồng Nhung',
    dob: '2001-08-19',
    email: 'hongnhung.dinh@gmail.com',
    phone: '0990123457',
    position1: 'Game Design Intern',
    university: 'HUTECH',
    yearOfStudy: 'Năm 4',
    major: 'Mỹ thuật đa phương tiện',
    gpa: 8.1,
    hasExperience: true,
    experienceDesc: '2 năm làm freelance UI/UX, có portfolio game mobile',
    portfolio: 'https://dribbble.com/hongnhung',
    fullTime: false,
    discoveryChannel: 'Instagram',
    submittedAt: '2026-05-09T10:30:00Z',
    batch: 3,
    pic: 'Minh',
    round1Result: 'Passed',
    round1Notes: 'Solid design portfolio',
  },
  {
    id: '021',
    name: 'Trương Minh Hiếu',
    dob: '2004-03-14',
    email: 'minhhieu.truong@uit.edu.vn',
    phone: '0901234569',
    position1: 'Data Analysis Intern',
    university: 'UIT',
    yearOfStudy: 'Năm 2',
    major: 'Hệ thống thông tin',
    gpa: 8.0,
    hasExperience: false,
    fullTime: true,
    discoveryChannel: 'Facebook',
    submittedAt: '2026-05-09T11:00:00Z',
    batch: 3,
    pic: 'Quỳnh',
    round1Result: 'Waiting list',
  },
  {
    id: '022',
    name: 'Lưu Thị Thanh Thảo',
    dob: '2002-10-27',
    email: 'thanhthao.luu@ueh.edu.vn',
    phone: '0912345680',
    position1: 'Game User Acquisition Intern',
    university: 'UEH',
    yearOfStudy: 'Năm 4',
    major: 'Marketing',
    gpa: 7.7,
    hasExperience: true,
    experienceDesc: 'Social media manager cho 2 game studio nhỏ',
    fullTime: true,
    discoveryChannel: 'Bạn bè giới thiệu',
    submittedAt: '2026-05-09T14:15:00Z',
    batch: 3,
    pic: 'Nhiên',
    round1Result: 'Failed',
    round1Notes: 'Limited game marketing knowledge',
  },
  {
    id: '023',
    name: 'Phùng Văn An',
    dob: '2003-01-06',
    email: 'vanan.phung@gmail.com',
    phone: '0923456791',
    position1: 'Unity Development Intern',
    position2: 'Game Quality Assurance Intern',
    university: 'FPT University',
    yearOfStudy: 'Năm 3',
    major: 'Kỹ thuật phần mềm',
    gpa: 9.2,
    hasExperience: true,
    experienceDesc: 'Intern Unity developer tại Amanotes 5 tháng',
    portfolio: 'https://github.com/vanan-phung',
    fullTime: true,
    discoveryChannel: 'LinkedIn',
    submittedAt: '2026-05-09T15:00:00Z',
    batch: 3,
    pic: 'Yến',
    round1Result: 'Passed',
    round1Notes: 'Amanotes experience is a major plus',
    round2Result: 'Passed',
  },
  {
    id: '024',
    name: 'Kiều Thị Minh Châu',
    dob: '2003-07-11',
    email: 'minhchau.kieu@gmail.com',
    phone: '0934567892',
    position1: 'Human Resources Intern',
    university: 'HCMUT',
    yearOfStudy: 'Năm 3',
    major: 'Quản lý kỹ thuật',
    gpa: 7.3,
    hasExperience: false,
    fullTime: false,
    discoveryChannel: 'Zalo',
    submittedAt: '2026-05-09T16:00:00Z',
    batch: 3,
    pic: 'Minh',
    round1Result: 'Failed',
  },
  {
    id: '025',
    name: 'Lê Ngọc Bảo Long',
    dob: '2002-04-24',
    email: 'baolong.le@huflit.edu.vn',
    phone: '0945678903',
    position1: 'AI Engineering Intern',
    university: 'HUFLIT',
    yearOfStudy: 'Năm 4',
    major: 'Công nghệ thông tin',
    gpa: 6.9,
    hasExperience: true,
    experienceDesc: 'Python developer cho dự án nhận diện khuôn mặt',
    portfolio: 'https://github.com/baolong-le',
    fullTime: true,
    discoveryChannel: 'Facebook',
    submittedAt: '2026-05-09T09:00:00Z',
    batch: 3,
    pic: 'Quỳnh',
    round1Result: 'Failed',
    round1Notes: 'GPA too low',
  },
  {
    id: '026',
    name: 'Tô Thị Kim Cương',
    dob: '2004-02-14',
    email: 'kimcuong.to@gmail.com',
    phone: '0956789014',
    position1: 'Game Design Intern',
    university: 'RMIT Vietnam',
    yearOfStudy: 'Năm 2',
    major: 'Communication Design',
    gpa: 8.6,
    hasExperience: false,
    portfolio: 'https://www.artstation.com/kimcuong',
    fullTime: true,
    discoveryChannel: 'Instagram',
    submittedAt: '2026-05-09T10:00:00Z',
    batch: 3,
    pic: 'Nhiên',
    round1Result: 'Passed',
    round1Notes: 'Exceptional artistic portfolio',
  },
  {
    id: '027',
    name: 'Hà Đình Nhân',
    dob: '2001-11-08',
    email: 'dinhnhan.ha@neu.edu.vn',
    phone: '0967890125',
    position1: 'Data Analysis Intern',
    position2: 'AI Engineering Intern',
    university: 'NEU',
    yearOfStudy: 'Năm 4',
    major: 'Công nghệ thông tin',
    gpa: 8.9,
    hasExperience: true,
    experienceDesc: 'Data analyst tại VNG 6 tháng, chuyên SQL và Python',
    portfolio: 'https://github.com/dinhnhan-ha',
    fullTime: true,
    discoveryChannel: 'LinkedIn',
    submittedAt: '2026-05-09T11:30:00Z',
    batch: 3,
    pic: 'Yến',
    round1Result: 'Passed',
    round1Notes: 'VNG experience highly relevant',
    round2Result: 'Passed',
  },
  {
    id: '028',
    name: 'Nguyễn Thảo Linh',
    dob: '2003-08-29',
    email: 'thaolin.nguyen@gmail.com',
    phone: '0978901236',
    position1: 'Game Quality Assurance Intern',
    university: 'HUTECH',
    yearOfStudy: 'Năm 3',
    major: 'Kỹ thuật phần mềm',
    gpa: 7.8,
    hasExperience: false,
    fullTime: true,
    discoveryChannel: 'TikTok',
    submittedAt: '2026-05-09T12:00:00Z',
    batch: 3,
    pic: 'Minh',
    round1Result: 'Waiting list',
    round1Notes: 'Good testing aptitude shown in assessment',
  },
  {
    id: '029',
    name: 'Dương Hoàng Phúc',
    dob: '2002-05-16',
    email: 'hoangphuc.duong@hcmut.edu.vn',
    phone: '0989012347',
    position1: 'Unity Development Intern',
    university: 'HCMUT',
    yearOfStudy: 'Năm 4',
    major: 'Khoa học máy tính',
    gpa: 8.5,
    hasExperience: true,
    experienceDesc: 'C# developer, tham gia phát triển 3D game với nhóm 4 người',
    portfolio: 'https://github.com/hoangphuc-duong',
    fullTime: true,
    discoveryChannel: 'Bạn bè giới thiệu',
    submittedAt: '2026-05-09T13:30:00Z',
    batch: 3,
    pic: 'Quỳnh',
    round1Result: 'Passed',
    round1Notes: '3D game experience very relevant',
    round2Result: 'Waiting list',
  },
  {
    id: '030',
    name: 'Mai Thị Bích Phương',
    dob: '2003-02-10',
    email: 'bichphuong.mai@ueh.edu.vn',
    phone: '0990123458',
    position1: 'Game User Acquisition Intern',
    university: 'UEH',
    yearOfStudy: 'Năm 3',
    major: 'Quản trị Marketing',
    gpa: 8.3,
    hasExperience: true,
    experienceDesc: 'Performance marketing intern tại VNG Mobile 4 tháng',
    fullTime: false,
    discoveryChannel: 'Facebook',
    submittedAt: '2026-05-09T14:00:00Z',
    batch: 3,
    pic: 'Nhiên',
    round1Result: 'Passed',
    round1Notes: 'VNG experience a strong plus for game UA',
  },
  {
    id: '031',
    name: 'Chu Đức Thịnh',
    dob: '2004-06-22',
    email: 'ducthinh.chu@gmail.com',
    phone: '0901234570',
    position1: 'AI Engineering Intern',
    university: 'UIT',
    yearOfStudy: 'Năm 2',
    major: 'Trí tuệ nhân tạo',
    gpa: 8.7,
    hasExperience: true,
    experienceDesc: 'Nghiên cứu NLP tại phòng lab trường, đã publish 1 bài báo',
    portfolio: 'https://github.com/ducthinh-chu',
    fullTime: true,
    discoveryChannel: 'Discord community',
    submittedAt: '2026-05-09T08:00:00Z',
    batch: 3,
    pic: 'Yến',
    round1Result: 'Passed',
    round1Notes: 'Research publication impressive for Year 2',
    round2Result: 'Passed',
  },
  {
    id: '032',
    name: 'Nghiêm Thị Phương Linh',
    dob: '2002-09-04',
    email: 'phuonglinh.nghiem@fpt.edu.vn',
    phone: '0912345681',
    position1: 'Human Resources Intern',
    position2: 'Data Analysis Intern',
    university: 'FPT University',
    yearOfStudy: 'Năm 4',
    major: 'Quản trị nhân lực',
    gpa: 9.0,
    hasExperience: true,
    experienceDesc: 'HR Business Partner intern tại Samsung Việt Nam',
    fullTime: true,
    discoveryChannel: 'LinkedIn',
    submittedAt: '2026-05-09T09:30:00Z',
    batch: 3,
    pic: 'Minh',
    round1Result: 'Passed',
    round1Notes: 'Samsung HRBP experience outstanding',
    round2Result: 'Passed',
  },
  {
    id: '033',
    name: 'Tạ Văn Khiêm',
    dob: '2003-04-01',
    email: 'vankhiem.ta@gmail.com',
    phone: '0923456792',
    position1: 'Game Quality Assurance Intern',
    university: 'HUTECH',
    yearOfStudy: 'Năm 3',
    major: 'Công nghệ thông tin',
    gpa: 6.5,
    hasExperience: false,
    fullTime: true,
    discoveryChannel: 'Zalo',
    submittedAt: '2026-05-09T15:00:00Z',
    batch: 3,
    pic: 'Quỳnh',
    round1Result: 'Failed',
    round1Notes: 'Low GPA, no relevant experience',
  },
  {
    id: '034',
    name: 'Nguyễn Hải Yến',
    dob: '2001-12-31',
    email: 'haiyen.nguyen@hcmut.edu.vn',
    phone: '0934567893',
    position1: 'Data Analysis Intern',
    university: 'HCMUT',
    yearOfStudy: 'Năm 4',
    major: 'Kỹ thuật máy tính',
    gpa: 8.2,
    hasExperience: true,
    experienceDesc: 'Data engineering intern tại MoMo 5 tháng',
    portfolio: 'https://github.com/haiyen-nguyen',
    fullTime: true,
    discoveryChannel: 'Website công ty',
    submittedAt: '2026-05-09T11:00:00Z',
    batch: 3,
    pic: 'Nhiên',
    round1Result: 'Passed',
    round1Notes: 'MoMo data engineering background relevant',
  },
  {
    id: '035',
    name: 'Trần Văn Toàn',
    dob: '2003-11-18',
    email: 'vantoan.tran@gmail.com',
    phone: '0945678904',
    position1: 'Unity Development Intern',
    university: 'NEU',
    yearOfStudy: 'Năm 3',
    major: 'Công nghệ thông tin',
    gpa: 7.1,
    hasExperience: false,
    fullTime: false,
    discoveryChannel: 'Facebook',
    submittedAt: '2026-05-09T16:30:00Z',
    batch: 3,
    pic: 'Yến',
    round1Result: 'Failed',
    round1Notes: 'Weak Unity fundamentals',
  },
  {
    id: '036',
    name: 'Bùi Thị Hải Vân',
    dob: '2002-07-08',
    email: 'haivanb.bui@gmail.com',
    phone: '0956789015',
    position1: 'Game Design Intern',
    position2: 'Game User Acquisition Intern',
    university: 'HUFLIT',
    yearOfStudy: 'Năm 4',
    major: 'Truyền thông đa phương tiện',
    gpa: 7.6,
    hasExperience: true,
    experienceDesc: 'UX designer cho ứng dụng mobile, có kinh nghiệm với Unity UI',
    portfolio: 'https://behance.net/haivanb',
    fullTime: true,
    discoveryChannel: 'Instagram',
    submittedAt: '2026-05-01T12:00:00Z',
    batch: 2,
    pic: 'Minh',
    round1Result: 'Waiting list',
    round1Notes: 'Good design sense, lacks game-specific experience',
  },
  {
    id: '037',
    name: 'Lê Gia Khánh',
    dob: '2004-10-20',
    email: 'giakhanh.le@uit.edu.vn',
    phone: '0967890126',
    position1: 'AI Engineering Intern',
    university: 'UIT',
    yearOfStudy: 'Năm 2',
    major: 'Khoa học máy tính',
    gpa: 9.5,
    hasExperience: true,
    experienceDesc: 'Top 1 khóa AI, tham gia Google Summer of Code',
    portfolio: 'https://github.com/giakhanh-le',
    fullTime: true,
    discoveryChannel: 'Discord community',
    submittedAt: '2026-04-23T07:00:00Z',
    batch: 1,
    pic: 'Quỳnh',
    round1Result: 'Passed',
    round1Notes: 'Outstanding candidate - Google SoC experience',
    round2Result: 'Passed',
  },
  {
    id: '038',
    name: 'Vương Thị Mộng Kiều',
    dob: '2003-03-03',
    email: 'mongkieu.vuong@rmit.edu.vn',
    phone: '0978901237',
    position1: 'Human Resources Intern',
    university: 'RMIT Vietnam',
    yearOfStudy: 'Năm 3',
    major: 'Business Management',
    gpa: 7.9,
    hasExperience: false,
    fullTime: true,
    discoveryChannel: 'Email newsletter',
    submittedAt: '2026-05-01T11:00:00Z',
    batch: 2,
    pic: 'Nhiên',
    round1Result: 'Passed',
    round1Notes: 'Strong communication, RMIT training quality',
  },
  {
    id: '039',
    name: 'Hồ Quốc Thắng',
    dob: '2002-02-15',
    email: 'quocthang.ho@hcmut.edu.vn',
    phone: '0989012348',
    position1: 'Game User Acquisition Intern',
    university: 'HCMUT',
    yearOfStudy: 'Năm 4',
    major: 'Quản lý công nghiệp',
    gpa: 7.4,
    hasExperience: true,
    experienceDesc: 'Quản lý cộng đồng cho 2 kênh Discord game lớn (50k+ members)',
    fullTime: true,
    discoveryChannel: 'Discord community',
    submittedAt: '2026-05-09T12:30:00Z',
    batch: 3,
    pic: 'Yến',
    round1Result: 'Waiting list',
    round1Notes: 'Community management experience relevant for UA',
  },
  {
    id: '040',
    name: 'Phạm Ngọc Trâm',
    dob: '2003-06-26',
    email: 'ngoctram.pham@fpt.edu.vn',
    phone: '0990123459',
    position1: 'Data Analysis Intern',
    position2: 'Human Resources Intern',
    university: 'FPT University',
    yearOfStudy: 'Năm 3',
    major: 'Data Science',
    gpa: 8.8,
    hasExperience: true,
    experienceDesc: 'Kaggle competitions, top 5% global. Python, R, Tableau proficient',
    portfolio: 'https://kaggle.com/ngoctram',
    fullTime: true,
    discoveryChannel: 'LinkedIn',
    submittedAt: '2026-04-24T10:00:00Z',
    batch: 1,
    pic: 'Minh',
    round1Result: 'Passed',
    round1Notes: 'Kaggle ranking very strong signal',
    round2Result: 'Passed',
  },
]

// Summary statistics
export const dashboardStats = {
  totalApplicants: 646,
  batch1Count: 119,
  batch2Count: 343,
  batch3Count: 182,
  passedRound1: 127,
  failedRound1: 428,
  waitingListRound1: 91,
  passRate: Math.round((127 / 646) * 100 * 10) / 10,
  avgGpa:
    Math.round(
      (mockApplicants.reduce((sum, a) => sum + a.gpa, 0) / mockApplicants.length) * 10
    ) / 10,
}

export const positionBreakdown = [
  { position: 'AI Engineering', count: 145, short: 'AI Eng' },
  { position: 'Data Analysis', count: 112, short: 'Data' },
  { position: 'Game Design', count: 98, short: 'Game Design' },
  { position: 'Unity Dev', count: 87, short: 'Unity' },
  { position: 'Game UA', count: 89, short: 'Game UA' },
  { position: 'HR', count: 63, short: 'HR' },
  { position: 'Game QA', count: 52, short: 'QA' },
]

export const discoveryChannelBreakdown = [
  { channel: 'Facebook', count: 201 },
  { channel: 'LinkedIn', count: 148 },
  { channel: 'Discord', count: 112 },
  { channel: 'Bạn bè', count: 89 },
  { channel: 'TikTok', count: 54 },
  { channel: 'Instagram', count: 42 },
]
